services:
  goat-relayer-1:
    build: .
    image: goatnetwork/goat-relayer:latest
    container_name: goat-relayer-1
    env_file:
      - .env
    ports:
      - "8080:8080"
      - "50051:50051"
      - "4001:4001"
    volumes:
      - ./data/db:/app/db
    networks:
      goat-network:
        ipv4_address: 192.168.10.2

  goat-relayer-2:
    image: goatnetwork/goat-relayer:latest
    container_name: goat-relayer-2
    env_file:
      - .env
    environment:
      - LIBP2P_BOOT_NODES=/ip4/192.168.10.2/tcp/4001/p2p/12D3KooWPxRKQ8mrJspeyppXDbh8SdXq27jVD9p1CmVdi8nmPnq6
    ports:
      - "8180:8080"
      - "51051:50051"
      - "4101:4001"
    volumes:
      - ./data/db2:/app/db
    networks:
      goat-network:
        ipv4_address: 192.168.10.3

networks:
  goat-network:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.10.0/24
